version: '2.1'

services:
  ethereum-testnet:
    container_name: ethereum-testnet
    image: ethereum/client-go
    restart: always
    ports:
      - "8544:8545"
      - "30302:30303"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/.ethereum:/root/.ethereum
    command:
      - --testnet
      - --rpc
      - --rpcaddr=0.0.0.0
      - --rpcapi="net,web3,eth,shh,debug"
      - --nousb #禁用监控和管理USB硬件钱包
      # - --syncmode=full
